import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { playlists, playlistTracks } from "@/lib/db/schema";
import { eq, and, max as drizzleMax } from "drizzle-orm";

// POST /api/playlists/all-time-songs/add
//   Body: { trackId: number }
//
// Idempotent: if the "All-Time Songs" playlist doesn't exist, create
// it; if the track is already in it, no-op. Returns the playlist id
// and the resulting position. The name is the default; the user can
// rename via the normal playlist rename flow.
const DEFAULT_NAME = "All-Time Songs";
const DEFAULT_DESCRIPTION =
  "Tracks you've crowned with 5 Vynls. Curated automatically.";

export async function POST(request: NextRequest) {
  let body: { trackId?: unknown };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "invalid json body" }, { status: 400 });
  }
  const trackId = Number(body.trackId);
  if (!Number.isFinite(trackId) || trackId <= 0) {
    return NextResponse.json({ error: "trackId required" }, { status: 400 });
  }

  // Find or create the playlist. Match by name exactly — if the user
  // renamed it, we still want to keep adding to the same row, so we
  // also accept any playlist with a special marker description (TODO:
  // could add a dedicated "is_auto_curated_5star" column later;
  // for now name match is enough).
  let row = db
    .select()
    .from(playlists)
    .where(eq(playlists.name, DEFAULT_NAME))
    .get();

  if (!row) {
    const inserted = db
      .insert(playlists)
      .values({
        name: DEFAULT_NAME,
        description: DEFAULT_DESCRIPTION,
        isAutoGenerated: true,
      })
      .returning()
      .get();
    row = inserted;
  }

  if (!row) {
    return NextResponse.json(
      { error: "could not create or find the playlist" },
      { status: 500 }
    );
  }

  // Already in the playlist?
  const existing = db
    .select()
    .from(playlistTracks)
    .where(
      and(
        eq(playlistTracks.playlistId, row.id),
        eq(playlistTracks.trackId, trackId)
      )
    )
    .get();

  if (existing) {
    return NextResponse.json({
      playlistId: row.id,
      playlistName: row.name,
      added: false,
      reason: "already in playlist",
      position: existing.position,
    });
  }

  // Append at the end. Position is one-based; pick max+1.
  const maxRow = db
    .select({ max: drizzleMax(playlistTracks.position) })
    .from(playlistTracks)
    .where(eq(playlistTracks.playlistId, row.id))
    .get();
  const nextPosition = (maxRow?.max ?? 0) + 1;

  db.insert(playlistTracks)
    .values({
      playlistId: row.id,
      trackId,
      position: nextPosition,
    })
    .run();

  return NextResponse.json({
    playlistId: row.id,
    playlistName: row.name,
    added: true,
    position: nextPosition,
  });
}
