import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { playlists, playlistTracks, tracks, tasteProfile } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { generatePlaylist, generateCoverArtPrompt, generateCoverArt } from "@/lib/ai";
import * as fs from "fs";
import * as path from "path";

// Generation can run for a while (LLM + image gen + image download).
// Default Next 15 timeout is 30s which kills the response with
// "Channel Error" mid-flight. Give it room to breathe.
export const maxDuration = 300;
export const runtime = "nodejs";

export async function POST(request: NextRequest) {
  const { mood } = await request.json();

  if (!mood) {
    return NextResponse.json({ error: "Mood/activity required" }, { status: 400 });
  }

  const profiles = db.select().from(tasteProfile).all();
  const latest = profiles[profiles.length - 1];

  if (!latest) {
    return NextResponse.json(
      { error: "No taste profile. Complete discovery first." },
      { status: 400 }
    );
  }

  const availableTracks = db
    .select({
      id: tracks.id,
      title: tracks.title,
      artist: tracks.artist,
      genre: tracks.genre,
    })
    .from(tracks)
    .all();

  if (availableTracks.length === 0) {
    return NextResponse.json(
      { error: "No tracks in library. Scan your library first." },
      { status: 400 }
    );
  }

  try {
    const result = await generatePlaylist(
      latest.profileText,
      availableTracks.map((t) => ({
        id: t.id,
        title: t.title,
        artist: t.artist,
        genre: t.genre || undefined,
      })),
      mood
    );

    // Create the playlist
    const playlist = db
      .insert(playlists)
      .values({
        name: result.name,
        description: result.description,
        isAutoGenerated: true,
      })
      .returning()
      .get();

    // Add tracks
    const validTrackIds = result.trackIds.filter((id) =>
      availableTracks.some((t) => t.id === id)
    );

    for (let i = 0; i < validTrackIds.length; i++) {
      db.insert(playlistTracks)
        .values({
          playlistId: playlist.id,
          trackId: validTrackIds[i],
          position: i,
        })
        .run();
    }

    // Kick off cover art generation in the background — don't make the
    // user wait through another LLM call + Replicate inference + image
    // download. The playlist row is fully usable without a cover; the
    // image lands on the row in the DB once it finishes (next page
    // refresh picks it up). Previous behavior chained everything in one
    // request and hit the 30s "Channel Error" wall.
    const trackTitlesForCover = availableTracks
      .filter((t) => validTrackIds.includes(t.id))
      .map((t) => t.title);
    void (async () => {
      try {
        const artPrompt = await generateCoverArtPrompt(
          result.name,
          trackTitlesForCover,
          mood
        );
        const artUrl = await generateCoverArt(artPrompt);
        if (!artUrl) return;
        const response = await fetch(artUrl);
        const buffer = Buffer.from(await response.arrayBuffer());
        const coversDir = path.join(process.cwd(), "public", "covers");
        if (!fs.existsSync(coversDir)) fs.mkdirSync(coversDir, { recursive: true });
        const filename = `playlist-${playlist.id}.png`;
        fs.writeFileSync(path.join(coversDir, filename), buffer);
        db.update(playlists)
          .set({ coverPath: `/covers/${filename}` })
          .where(eq(playlists.id, playlist.id))
          .run();
      } catch (err) {
        console.error("Cover art background job failed (non-fatal):", err);
      }
    })();

    return NextResponse.json({
      ...playlist,
      coverPath: null,
      coverPending: true,
      trackCount: validTrackIds.length,
    });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to generate playlist", details: String(err) },
      { status: 500 }
    );
  }
}
