"use client";

import React, { useEffect, useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { usePlayerStore, Track as PlayerTrack } from "@/store/player";
import {
  Plus,
  ListMusic,
  Play,
  Sparkles,
  Trash2,
  Music,
  Loader2,
  GripVertical,
} from "lucide-react";
import Image from "next/image";
import { motion } from "framer-motion";
import { formatDuration } from "@/lib/utils";

interface PlaylistInfo {
  id: number;
  name: string;
  description?: string;
  coverPath?: string;
  trackCount: number;
  isAutoGenerated?: boolean;
  createdAt?: string;
}

interface PlaylistTrack {
  id: number;
  title: string;
  artist: string;
  album: string;
  duration: number;
  filePath: string;
  coverPath?: string;
  position: number;
}

export default function PlaylistsPage() {
  const [playlists, setPlaylists] = useState<PlaylistInfo[]>([]);
  const [selectedPlaylist, setSelectedPlaylist] = useState<number | null>(null);
  const [playlistTracks, setPlaylistTracks] = useState<PlaylistTrack[]>([]);
  const [newName, setNewName] = useState("");
  const [newDescription, setNewDescription] = useState("");
  const [generateMood, setGenerateMood] = useState("");
  const [generating, setGenerating] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [generateDialogOpen, setGenerateDialogOpen] = useState(false);
  const { setQueue } = usePlayerStore();

  const fetchPlaylists = useCallback(async () => {
    const res = await fetch("/api/playlists");
    const data = await res.json();
    setPlaylists(data.playlists || []);
  }, []);

  useEffect(() => {
    fetchPlaylists();
  }, [fetchPlaylists]);

  const fetchPlaylistTracks = async (id: number) => {
    const res = await fetch(`/api/playlists/${id}`);
    const data = await res.json();
    setPlaylistTracks(data.tracks || []);
    setSelectedPlaylist(id);
  };

  const createPlaylist = async () => {
    if (!newName) return;
    await fetch("/api/playlists", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newName, description: newDescription }),
    });
    setNewName("");
    setNewDescription("");
    setDialogOpen(false);
    fetchPlaylists();
  };

  const deletePlaylist = async (id: number) => {
    await fetch(`/api/playlists/${id}`, { method: "DELETE" });
    if (selectedPlaylist === id) {
      setSelectedPlaylist(null);
      setPlaylistTracks([]);
    }
    fetchPlaylists();
  };

  const generatePlaylist = async () => {
    if (!generateMood) return;
    setGenerating(true);
    try {
      await fetch("/api/playlists/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ mood: generateMood }),
      });
      setGenerateMood("");
      setGenerateDialogOpen(false);
      fetchPlaylists();
    } catch {}
    setGenerating(false);
  };

  const playPlaylist = (index = 0) => {
    const tracks: PlayerTrack[] = playlistTracks.map((t) => ({
      id: t.id,
      title: t.title,
      artist: t.artist,
      album: t.album,
      duration: t.duration,
      filePath: t.filePath,
      coverPath: t.coverPath,
      source: "local",
    }));
    setQueue(tracks, index);
  };

  const currentPlaylist = playlists.find((p) => p.id === selectedPlaylist);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Playlists</h1>
          <p className="text-muted-foreground mt-1">
            {playlists.length} playlists
          </p>
        </div>
        <div className="flex gap-2">
          <Dialog open={generateDialogOpen} onOpenChange={setGenerateDialogOpen}>
            <DialogTrigger asChild>
              <Button variant="outline">
                <Sparkles className="h-4 w-4 mr-2" />
                AI Generate
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Generate AI Playlist</DialogTitle>
              </DialogHeader>
              <div className="space-y-4 pt-4">
                <Input
                  placeholder="Mood or activity (e.g., 'chill evening', 'workout energy')"
                  value={generateMood}
                  onChange={(e) => setGenerateMood(e.target.value)}
                />
                <Button
                  onClick={generatePlaylist}
                  disabled={!generateMood || generating}
                  className="w-full"
                >
                  {generating ? (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Sparkles className="h-4 w-4 mr-2" />
                  )}
                  Generate Playlist
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                New Playlist
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Playlist</DialogTitle>
              </DialogHeader>
              <div className="space-y-4 pt-4">
                <Input
                  placeholder="Playlist name"
                  value={newName}
                  onChange={(e) => setNewName(e.target.value)}
                />
                <Input
                  placeholder="Description (optional)"
                  value={newDescription}
                  onChange={(e) => setNewDescription(e.target.value)}
                />
                <Button
                  onClick={createPlaylist}
                  disabled={!newName}
                  className="w-full"
                >
                  Create
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      <div className="flex gap-6">
        {/* Playlist Grid */}
        <div className="flex-1">
          {selectedPlaylist ? (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="space-y-4"
            >
              <div className="flex items-center gap-4">
                <Button
                  variant="ghost"
                  onClick={() => {
                    setSelectedPlaylist(null);
                    setPlaylistTracks([]);
                  }}
                >
                  Back
                </Button>
                <div className="flex-1">
                  <h2 className="text-2xl font-bold">
                    {currentPlaylist?.name}
                  </h2>
                  {currentPlaylist?.description && (
                    <p className="text-sm text-muted-foreground">
                      {currentPlaylist.description}
                    </p>
                  )}
                </div>
                <Button onClick={() => playPlaylist()}>
                  <Play className="h-4 w-4 mr-2" />
                  Play All
                </Button>
              </div>

              <Card>
                <CardContent className="p-0">
                  {playlistTracks.map((track, i) => (
                    <div
                      key={track.id}
                      className="flex items-center gap-4 px-4 py-2 hover:bg-secondary/30 transition-colors cursor-pointer group"
                      onClick={() => playPlaylist(i)}
                    >
                      <GripVertical className="h-4 w-4 text-muted-foreground opacity-0 group-hover:opacity-100" />
                      <span className="text-sm text-muted-foreground w-6 text-right group-hover:hidden">
                        {i + 1}
                      </span>
                      <Play className="h-4 w-4 hidden group-hover:block text-primary" />
                      <div className="w-10 h-10 rounded bg-secondary flex items-center justify-center shrink-0 overflow-hidden">
                        {track.coverPath ? (
                          <Image
                            src={track.coverPath}
                            alt={track.album}
                            width={40}
                            height={40}
                            className="object-cover"
                          />
                        ) : (
                          <Music className="h-4 w-4 text-muted-foreground" />
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium truncate">
                          {track.title}
                        </p>
                        <p className="text-xs text-muted-foreground truncate">
                          {track.artist}
                        </p>
                      </div>
                      <span className="text-sm text-muted-foreground">
                        {formatDuration(track.duration)}
                      </span>
                    </div>
                  ))}
                  {playlistTracks.length === 0 && (
                    <div className="py-12 text-center text-muted-foreground">
                      <ListMusic className="h-12 w-12 mx-auto mb-4 opacity-50" />
                      <p>This playlist is empty</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </motion.div>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
              {playlists.map((pl, i) => (
                <motion.div
                  key={pl.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                >
                  <Card
                    className="hover:bg-secondary/50 transition-colors cursor-pointer group relative"
                    onClick={() => fetchPlaylistTracks(pl.id)}
                  >
                    <CardContent className="p-4">
                      <div className="aspect-square rounded-lg bg-secondary mb-3 flex items-center justify-center overflow-hidden relative">
                        {pl.coverPath ? (
                          <Image
                            src={pl.coverPath}
                            alt={pl.name}
                            fill
                            className="object-cover"
                          />
                        ) : (
                          <ListMusic className="h-10 w-10 text-muted-foreground" />
                        )}
                        <div className="absolute bottom-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                          <Button
                            size="icon"
                            className="rounded-full h-10 w-10 shadow-lg"
                          >
                            <Play className="h-4 w-4 ml-0.5" />
                          </Button>
                        </div>
                      </div>
                      <div className="flex items-start justify-between">
                        <div className="min-w-0 flex-1">
                          <p className="font-medium truncate">{pl.name}</p>
                          <p className="text-xs text-muted-foreground">
                            {pl.trackCount} tracks
                            {pl.isAutoGenerated && (
                              <Badge
                                variant="outline"
                                className="ml-2 text-xs"
                              >
                                AI
                              </Badge>
                            )}
                          </p>
                        </div>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-6 w-6 opacity-0 group-hover:opacity-100"
                          onClick={(e) => {
                            e.stopPropagation();
                            deletePlaylist(pl.id);
                          }}
                        >
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}

              {playlists.length === 0 && (
                <div className="col-span-full py-16 text-center">
                  <ListMusic className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
                  <p className="text-lg text-muted-foreground">
                    No playlists yet
                  </p>
                  <p className="text-sm text-muted-foreground mt-1">
                    Create one manually or let AI generate one for you
                  </p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
