/**
 * POST /api/spotify/migration/create-playlist
 *
 * Create a Vynl playlist from a Spotify source. Pulls every spotify_track
 * that's linked to the source AND has local_track_id IS NOT NULL (i.e. is
 * already in your library), and creates a Vynl playlist with those tracks
 * in chronological order.
 *
 * Body:
 *   { spotifyPlaylistId: number | "liked",  // -1 / "liked" = Liked Songs
 *     name?: string                          // override playlist name }
 *
 * Returns:
 *   { playlistId, name, addedCount, missing, totalInSource }
 *
 * Replaces phase 6 ("mirror playlists") of the old destructive extract
 * pipeline — but explicitly user-driven instead of automatic.
 */

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  spotifyPlaylists,
  spotifyPlaylistTracks,
  spotifyTracks,
  playlists,
  playlistTracks,
} from "@/lib/db/schema";
import { eq, desc, sql } from "drizzle-orm";

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => ({}));
  const rawId = body?.spotifyPlaylistId;
  const overrideName: string | undefined = typeof body?.name === "string" ? body.name : undefined;

  if (rawId === undefined || rawId === null) {
    return NextResponse.json({ error: "spotifyPlaylistId required" }, { status: 400 });
  }

  // "liked" / -1 → Liked Songs synthetic playlist
  const isLiked = rawId === "liked" || rawId === -1;

  let sourceName = "Spotify Migration";
  let totalInSource = 0;
  let matchedRows: Array<{ trackId: number; position: number }> = [];

  if (isLiked) {
    sourceName = overrideName || "Spotify Liked Songs";
    const all = db
      .select({
        trackId: spotifyTracks.localTrackId,
        // Stable order: by insertion order in spotify_tracks (id ASC).
        position: spotifyTracks.id,
      })
      .from(spotifyTracks)
      .where(sql`${spotifyTracks.isLikedSong} = 1`)
      .orderBy(spotifyTracks.id)
      .all();
    totalInSource = all.length;
    matchedRows = all
      .filter((r): r is { trackId: number; position: number } => r.trackId != null)
      .map((r, i) => ({ trackId: r.trackId, position: i }));
  } else {
    const pid = typeof rawId === "number" ? rawId : parseInt(String(rawId), 10);
    if (!Number.isFinite(pid)) {
      return NextResponse.json({ error: "invalid spotifyPlaylistId" }, { status: 400 });
    }

    const sp = db
      .select({ name: spotifyPlaylists.name })
      .from(spotifyPlaylists)
      .where(eq(spotifyPlaylists.id, pid))
      .get();
    if (!sp) {
      return NextResponse.json({ error: `Spotify playlist ${pid} not found` }, { status: 404 });
    }
    sourceName = overrideName || sp.name;

    // Join + filter: matched-only, in source order.
    const rows = db
      .select({
        trackId: spotifyTracks.localTrackId,
        position: spotifyPlaylistTracks.position,
      })
      .from(spotifyPlaylistTracks)
      .innerJoin(spotifyTracks, eq(spotifyTracks.id, spotifyPlaylistTracks.spotifyTrackId))
      .where(eq(spotifyPlaylistTracks.spotifyPlaylistId, pid))
      .orderBy(spotifyPlaylistTracks.position)
      .all();
    totalInSource = rows.length;
    matchedRows = rows
      .filter((r): r is { trackId: number; position: number } => r.trackId != null)
      .map((r, i) => ({ trackId: r.trackId, position: i }));
  }

  if (matchedRows.length === 0) {
    return NextResponse.json(
      {
        error:
          "No matched tracks for this source. Download missing tracks first via the migration wizard.",
        totalInSource,
      },
      { status: 400 }
    );
  }

  // Create the Vynl playlist. is_auto_generated = true so /playlists UI can
  // distinguish wizard-created from user-curated lists later.
  const plResult = db
    .insert(playlists)
    .values({
      name: sourceName,
      description: `Mirrored from Spotify · ${matchedRows.length} of ${totalInSource} tracks in your library`,
      isAutoGenerated: true,
    })
    .run();
  const newPlaylistId = Number(plResult.lastInsertRowid);

  // Bulk insert tracks in position order. Drizzle insert-many.
  db.insert(playlistTracks)
    .values(
      matchedRows.map((r) => ({
        playlistId: newPlaylistId,
        trackId: r.trackId,
        position: r.position,
      }))
    )
    .run();

  // For real Spotify playlists, also link back so the migration UI can show
  // "✓ Mirrored to '...'" next time.
  if (!isLiked) {
    const pid = typeof rawId === "number" ? rawId : parseInt(String(rawId), 10);
    db.update(spotifyPlaylists)
      .set({ vynlPlaylistId: newPlaylistId })
      .where(eq(spotifyPlaylists.id, pid))
      .run();
  }

  void desc; // silence unused-import warning if drizzle tree-shaker complains
  return NextResponse.json({
    playlistId: newPlaylistId,
    name: sourceName,
    addedCount: matchedRows.length,
    missing: totalInSource - matchedRows.length,
    totalInSource,
  });
}
