import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { tracks } from "@/lib/db/schema";

// Helper: access a field by camelCase or snake_case
function f(obj: Record<string, unknown>, camel: string, snake: string): unknown {
  return obj[camel] ?? obj[snake];
}

// Import user data from another Vynl instance
// POST with JSON body from /api/data/export, plus ?source=http://source:3101 to auto-fetch track mapping
export async function POST(request: NextRequest) {
  try {
    const sourceUrl = request.nextUrl.searchParams.get("source");

    let exportData: Record<string, unknown>;
    let trackMap: Record<string, string> | undefined;

    if (sourceUrl) {
      const resp = await fetch(`${sourceUrl}/api/data/export`);
      if (!resp.ok) return NextResponse.json({ error: `Failed to fetch from ${sourceUrl}` }, { status: 502 });
      exportData = await resp.json();

      const tracksResp = await fetch(`${sourceUrl}/api/data/track-map`);
      if (tracksResp.ok) {
        trackMap = await tracksResp.json();
      }
    } else {
      exportData = await request.json();
      trackMap = exportData.trackMap as Record<string, string> | undefined;
    }

    const sqlite = (db as any).session?.client || (db as any).$client;

    // Build source track_id → local track_id mapping
    const idMap = new Map<number, number>();

    if (trackMap) {
      const pathRemap = process.env.BEETS_PATH_REMAP;
      const remapRules: { from: string; to: string }[] = [];
      if (pathRemap) {
        for (const rule of pathRemap.split(";")) {
          const [from, to] = rule.split("::");
          if (from && to) remapRules.push({ from, to });
        }
      }

      // Build a local file_path → track_id index for fast lookup
      const allLocal = db.select({ id: tracks.id, filePath: tracks.filePath }).from(tracks).all();
      const localByPath = new Map<string, number>();
      for (const t of allLocal) {
        localByPath.set(t.filePath, t.id);
      }

      for (const [sourceId, sourcePath] of Object.entries(trackMap)) {
        // Direct match
        const directMatch = localByPath.get(sourcePath);
        if (directMatch) {
          idMap.set(Number(sourceId), directMatch);
          continue;
        }

        // Try remap rules (source paths use different prefixes)
        for (const rule of remapRules) {
          if (sourcePath.startsWith(rule.from + "/")) {
            const testPath = rule.to + sourcePath.slice(rule.from.length);
            const match = localByPath.get(testPath);
            if (match) {
              idMap.set(Number(sourceId), match);
              break;
            }
          }
        }
      }
    }

    let playlistsImported = 0;
    let ratingsImported = 0;
    let historyImported = 0;
    let lyricsImported = 0;
    let settingsImported = 0;

    // Import playlists (handle both camelCase and snake_case keys)
    const playlistIdMap = new Map<number, number>();
    const playlists = (exportData.playlists || []) as Record<string, unknown>[];
    for (const pl of playlists) {
      const srcId = f(pl, "id", "id") as number;
      const result = sqlite.prepare(
        `INSERT OR IGNORE INTO playlists (name, description, cover_path, is_auto_generated, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?)`
      ).run(
        f(pl, "name", "name"),
        f(pl, "description", "description") || null,
        f(pl, "coverPath", "cover_path") || null,
        f(pl, "isAutoGenerated", "is_auto_generated") || 0,
        f(pl, "createdAt", "created_at") || null,
        f(pl, "updatedAt", "updated_at") || null,
      );

      if (result.changes > 0) {
        playlistIdMap.set(srcId, result.lastInsertRowid as number);
        playlistsImported++;
      }
    }

    // Import playlist tracks
    let playlistTracksImported = 0;
    const pTracks = (exportData.playlistTracks || []) as Record<string, unknown>[];
    for (const pt of pTracks) {
      const srcPlaylistId = (f(pt, "playlistId", "playlist_id") ?? 0) as number;
      const srcTrackId = (f(pt, "trackId", "track_id") ?? 0) as number;
      const newPlaylistId = playlistIdMap.get(srcPlaylistId);
      const newTrackId = idMap.get(srcTrackId);
      if (newPlaylistId && newTrackId) {
        try {
          sqlite.prepare(
            `INSERT OR IGNORE INTO playlist_tracks (playlist_id, track_id, position, added_at)
             VALUES (?, ?, ?, ?)`
          ).run(newPlaylistId, newTrackId, f(pt, "position", "position"), f(pt, "addedAt", "added_at") || null);
          playlistTracksImported++;
        } catch { /* skip duplicates */ }
      }
    }

    // Import track ratings
    const ratings = (exportData.trackRatings || []) as Record<string, unknown>[];
    for (const tr of ratings) {
      const srcTrackId = (f(tr, "trackId", "track_id") ?? 0) as number;
      const newTrackId = idMap.get(srcTrackId);
      if (newTrackId) {
        try {
          sqlite.prepare(
            `INSERT OR REPLACE INTO track_ratings (track_id, rating, rated_at) VALUES (?, ?, ?)`
          ).run(newTrackId, f(tr, "rating", "rating"), f(tr, "ratedAt", "rated_at") || null);
          ratingsImported++;
        } catch { /* skip */ }
      }
    }

    // Import listening history
    const history = (exportData.listeningHistory || []) as Record<string, unknown>[];
    for (const lh of history) {
      const srcTrackId = f(lh, "trackId", "track_id") as number | undefined;
      const newTrackId = srcTrackId ? idMap.get(srcTrackId) : null;
      try {
        sqlite.prepare(
          `INSERT INTO listening_history (track_id, track_title, track_artist, source, played_at, duration, listened_duration, output_target)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
        ).run(
          newTrackId || null,
          f(lh, "trackTitle", "track_title"),
          f(lh, "trackArtist", "track_artist"),
          f(lh, "source", "source") || "local",
          f(lh, "playedAt", "played_at") || null,
          f(lh, "duration", "duration") || null,
          f(lh, "listenedDuration", "listened_duration") || null,
          f(lh, "outputTarget", "output_target") || "browser",
        );
        historyImported++;
      } catch { /* skip */ }
    }

    // Import lyrics
    const lyrics = (exportData.trackLyrics || []) as Record<string, unknown>[];
    for (const tl of lyrics) {
      const srcTrackId = (f(tl, "trackId", "track_id") ?? 0) as number;
      const newTrackId = idMap.get(srcTrackId);
      if (newTrackId) {
        try {
          sqlite.prepare(
            `INSERT OR REPLACE INTO track_lyrics (track_id, content, format, source, fetched_at)
             VALUES (?, ?, ?, ?, ?)`
          ).run(newTrackId, f(tl, "content", "content"), f(tl, "format", "format"), f(tl, "source", "source"), f(tl, "fetchedAt", "fetched_at") || null);
          lyricsImported++;
        } catch { /* skip */ }
      }
    }

    // Import settings
    const settingsData = (exportData.settings || []) as Record<string, unknown>[];
    for (const s of settingsData) {
      try {
        sqlite.prepare(
          `INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)`
        ).run(f(s, "key", "key"), f(s, "value", "value"));
        settingsImported++;
      } catch { /* skip */ }
    }

    return NextResponse.json({
      tracksMapped: idMap.size,
      playlistsImported,
      playlistTracksImported,
      ratingsImported,
      historyImported,
      lyricsImported,
      settingsImported,
    });
  } catch (err) {
    console.error("Import error:", err);
    return NextResponse.json(
      { error: "Import failed", details: String(err) },
      { status: 500 }
    );
  }
}
